[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"

[command]
    publish = "static"

[[redirects]]
    from = "/*"
    to = "/static/:splat"
    force = true
    status = 301

[[redirects]]
    from = "https://suhailmoeen.app"
    to = "https://suhailmoeen.netlify.app"
    force = true
    status = 301