[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"

[command]
    included_files = ["static/**", "static/**.json"]
    publish = "./site"

[[redirects]]
    from = "/app/*"
    status = 200
    force = true
    to = "/.netlify/functions/app/:splat"