[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"

[command]
    publish = "static"

[[redirects]]
    from = "/static/*"
    to = "/:splat"
    force = true
    status = 301